import { env } from './env'

export const X402_CONFIG = {
  USDC_DEVNET_MINT: env.NEXT_PUBLIC_USDC_DEVNET_MINT,
  TREASURY_ADDRESS: env.NEXT_PUBLIC_TREASURY_ADDRESS,
  REQUIRED_AMOUNT: Math.floor(
    env.NEXT_PUBLIC_PAYMENT_AMOUNT_USD * Math.pow(10, env.NEXT_PUBLIC_USDC_DECIMALS),
  ).toString(),
  FEE_PAYER: env.NEXT_PUBLIC_FEE_PAYER,
  FACILITATOR_BASE_URL: env.FACILITATOR_URL,
  COOKIE_NAME: env.COOKIE_NAME,
  COOKIE_MAX_AGE: env.COOKIE_MAX_AGE,
} as const
