/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { STAKING_TEMPLATE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const INITIALIZE_POOL_DISCRIMINATOR = new Uint8Array([
  95, 180, 10, 172, 84, 174, 232, 40,
]);

export function getInitializePoolDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_POOL_DISCRIMINATOR,
  );
}

export type InitializePoolInstruction<
  TProgram extends string = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountTokenMint extends string
        ? WritableAccount<TAccountTokenMint>
        : TAccountTokenMint,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializePoolInstructionData = {
  discriminator: ReadonlyUint8Array;
  rewardsPerStake: number;
  maxStake: bigint;
  freezePeriod: bigint;
};

export type InitializePoolInstructionDataArgs = {
  rewardsPerStake: number;
  maxStake: number | bigint;
  freezePeriod: number | bigint;
};

export function getInitializePoolInstructionDataEncoder(): FixedSizeEncoder<InitializePoolInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["rewardsPerStake", getU8Encoder()],
      ["maxStake", getU64Encoder()],
      ["freezePeriod", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_POOL_DISCRIMINATOR }),
  );
}

export function getInitializePoolInstructionDataDecoder(): FixedSizeDecoder<InitializePoolInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["rewardsPerStake", getU8Decoder()],
    ["maxStake", getU64Decoder()],
    ["freezePeriod", getI64Decoder()],
  ]);
}

export function getInitializePoolInstructionDataCodec(): FixedSizeCodec<
  InitializePoolInstructionDataArgs,
  InitializePoolInstructionData
> {
  return combineCodec(
    getInitializePoolInstructionDataEncoder(),
    getInitializePoolInstructionDataDecoder(),
  );
}

export type InitializePoolAsyncInput<
  TAccountAdmin extends string = string,
  TAccountTokenMint extends string = string,
  TAccountVault extends string = string,
  TAccountConfig extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  /** reward / receipt mint — authority is the config PDA */
  tokenMint?: Address<TAccountTokenMint>;
  /** SOL vault PDA — holds all staked lamports */
  vault?: Address<TAccountVault>;
  config?: Address<TAccountConfig>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  rewardsPerStake: InitializePoolInstructionDataArgs["rewardsPerStake"];
  maxStake: InitializePoolInstructionDataArgs["maxStake"];
  freezePeriod: InitializePoolInstructionDataArgs["freezePeriod"];
};

export async function getInitializePoolInstructionAsync<
  TAccountAdmin extends string,
  TAccountTokenMint extends string,
  TAccountVault extends string,
  TAccountConfig extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
>(
  input: InitializePoolAsyncInput<
    TAccountAdmin,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitializePoolInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAKING_TEMPLATE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenMint.value) {
    accounts.tokenMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 111, 107, 101, 110, 95, 109, 105, 110, 116]),
        ),
      ],
    });
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
      ],
    });
  }
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializePoolInstructionDataEncoder().encode(
      args as InitializePoolInstructionDataArgs,
    ),
    programAddress,
  } as InitializePoolInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type InitializePoolInput<
  TAccountAdmin extends string = string,
  TAccountTokenMint extends string = string,
  TAccountVault extends string = string,
  TAccountConfig extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  /** reward / receipt mint — authority is the config PDA */
  tokenMint: Address<TAccountTokenMint>;
  /** SOL vault PDA — holds all staked lamports */
  vault: Address<TAccountVault>;
  config: Address<TAccountConfig>;
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  rewardsPerStake: InitializePoolInstructionDataArgs["rewardsPerStake"];
  maxStake: InitializePoolInstructionDataArgs["maxStake"];
  freezePeriod: InitializePoolInstructionDataArgs["freezePeriod"];
};

export function getInitializePoolInstruction<
  TAccountAdmin extends string,
  TAccountTokenMint extends string,
  TAccountVault extends string,
  TAccountConfig extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
>(
  input: InitializePoolInput<
    TAccountAdmin,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitializePoolInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountTokenMint,
  TAccountVault,
  TAccountConfig,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? STAKING_TEMPLATE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializePoolInstructionDataEncoder().encode(
      args as InitializePoolInstructionDataArgs,
    ),
    programAddress,
  } as InitializePoolInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedInitializePoolInstruction<
  TProgram extends string = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    /** reward / receipt mint — authority is the config PDA */
    tokenMint: TAccountMetas[1];
    /** SOL vault PDA — holds all staked lamports */
    vault: TAccountMetas[2];
    config: TAccountMetas[3];
    tokenProgram: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: InitializePoolInstructionData;
};

export function parseInitializePoolInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitializePoolInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      tokenMint: getNextAccount(),
      vault: getNextAccount(),
      config: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializePoolInstructionDataDecoder().decode(instruction.data),
  };
}
