/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit'
import { STAKING_TEMPLATE_PROGRAM_ADDRESS } from '../programs'
import { expectAddress, expectSome, getAccountMetaFactory, type ResolvedAccount } from '../shared'

export const STAKE_DISCRIMINATOR = new Uint8Array([206, 176, 202, 18, 200, 209, 179, 108])

export function getStakeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(STAKE_DISCRIMINATOR)
}

export type StakeInstruction<
  TProgram extends string = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountUserAccount extends string | AccountMeta<string> = string,
  TAccountStakeAccount extends string | AccountMeta<string> = string,
  TAccountUserTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenMint extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends string | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountUserAccount extends string ? WritableAccount<TAccountUserAccount> : TAccountUserAccount,
      TAccountStakeAccount extends string ? WritableAccount<TAccountStakeAccount> : TAccountStakeAccount,
      TAccountUserTokenAccount extends string ? WritableAccount<TAccountUserTokenAccount> : TAccountUserTokenAccount,
      TAccountTokenMint extends string ? WritableAccount<TAccountTokenMint> : TAccountTokenMint,
      TAccountVault extends string ? WritableAccount<TAccountVault> : TAccountVault,
      TAccountConfig extends string ? ReadonlyAccount<TAccountConfig> : TAccountConfig,
      TAccountTokenProgram extends string ? ReadonlyAccount<TAccountTokenProgram> : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string ? ReadonlyAccount<TAccountSystemProgram> : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >

export type StakeInstructionData = {
  discriminator: ReadonlyUint8Array
  id: bigint
  amount: bigint
}

export type StakeInstructionDataArgs = {
  id: number | bigint
  amount: number | bigint
}

export function getStakeInstructionDataEncoder(): FixedSizeEncoder<StakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['id', getU64Encoder()],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: STAKE_DISCRIMINATOR }),
  )
}

export function getStakeInstructionDataDecoder(): FixedSizeDecoder<StakeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['id', getU64Decoder()],
    ['amount', getU64Decoder()],
  ])
}

export function getStakeInstructionDataCodec(): FixedSizeCodec<StakeInstructionDataArgs, StakeInstructionData> {
  return combineCodec(getStakeInstructionDataEncoder(), getStakeInstructionDataDecoder())
}

export type StakeAsyncInput<
  TAccountUser extends string = string,
  TAccountUserAccount extends string = string,
  TAccountStakeAccount extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountTokenMint extends string = string,
  TAccountVault extends string = string,
  TAccountConfig extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>
  /** created on first stake, reused on subsequent ones */
  userAccount?: Address<TAccountUserAccount>
  /** one per stake — seed includes `id` so users can stake multiple times */
  stakeAccount?: Address<TAccountStakeAccount>
  userTokenAccount?: Address<TAccountUserTokenAccount>
  tokenMint?: Address<TAccountTokenMint>
  vault?: Address<TAccountVault>
  config?: Address<TAccountConfig>
  tokenProgram?: Address<TAccountTokenProgram>
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
  systemProgram?: Address<TAccountSystemProgram>
  id: StakeInstructionDataArgs['id']
  amount: StakeInstructionDataArgs['amount']
}

export async function getStakeInstructionAsync<
  TAccountUser extends string,
  TAccountUserAccount extends string,
  TAccountStakeAccount extends string,
  TAccountUserTokenAccount extends string,
  TAccountTokenMint extends string,
  TAccountVault extends string,
  TAccountConfig extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
>(
  input: StakeAsyncInput<
    TAccountUser,
    TAccountUserAccount,
    TAccountStakeAccount,
    TAccountUserTokenAccount,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  StakeInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountUserAccount,
    TAccountStakeAccount,
    TAccountUserTokenAccount,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAKING_TEMPLATE_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    stakeAccount: { value: input.stakeAccount ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.userAccount.value) {
    accounts.userAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([117, 115, 101, 114])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    })
  }
  if (!accounts.stakeAccount.value) {
    accounts.stakeAccount.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([115, 116, 97, 107, 101])),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
        getU64Encoder().encode(expectSome(args.id)),
      ],
    })
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>
  }
  if (!accounts.tokenMint.value) {
    accounts.tokenMint.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getBytesEncoder().encode(new Uint8Array([116, 111, 107, 101, 110, 95, 109, 105, 110, 116]))],
    })
  }
  if (!accounts.userTokenAccount.value) {
    accounts.userTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenMint.value)),
      ],
    })
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116]))],
    })
  }
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103]))],
    })
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.stakeAccount),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getStakeInstructionDataEncoder().encode(args as StakeInstructionDataArgs),
    programAddress,
  } as StakeInstruction<TProgramAddress, TAccountUser, TAccountUserAccount, TAccountStakeAccount, TAccountUserTokenAccount, TAccountTokenMint, TAccountVault, TAccountConfig, TAccountTokenProgram, TAccountAssociatedTokenProgram, TAccountSystemProgram>)
}

export type StakeInput<
  TAccountUser extends string = string,
  TAccountUserAccount extends string = string,
  TAccountStakeAccount extends string = string,
  TAccountUserTokenAccount extends string = string,
  TAccountTokenMint extends string = string,
  TAccountVault extends string = string,
  TAccountConfig extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>
  /** created on first stake, reused on subsequent ones */
  userAccount: Address<TAccountUserAccount>
  /** one per stake — seed includes `id` so users can stake multiple times */
  stakeAccount: Address<TAccountStakeAccount>
  userTokenAccount: Address<TAccountUserTokenAccount>
  tokenMint: Address<TAccountTokenMint>
  vault: Address<TAccountVault>
  config: Address<TAccountConfig>
  tokenProgram?: Address<TAccountTokenProgram>
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>
  systemProgram?: Address<TAccountSystemProgram>
  id: StakeInstructionDataArgs['id']
  amount: StakeInstructionDataArgs['amount']
}

export function getStakeInstruction<
  TAccountUser extends string,
  TAccountUserAccount extends string,
  TAccountStakeAccount extends string,
  TAccountUserTokenAccount extends string,
  TAccountTokenMint extends string,
  TAccountVault extends string,
  TAccountConfig extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
>(
  input: StakeInput<
    TAccountUser,
    TAccountUserAccount,
    TAccountStakeAccount,
    TAccountUserTokenAccount,
    TAccountTokenMint,
    TAccountVault,
    TAccountConfig,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): StakeInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountUserAccount,
  TAccountStakeAccount,
  TAccountUserTokenAccount,
  TAccountTokenMint,
  TAccountVault,
  TAccountConfig,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? STAKING_TEMPLATE_PROGRAM_ADDRESS

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    userAccount: { value: input.userAccount ?? null, isWritable: true },
    stakeAccount: { value: input.stakeAccount ?? null, isWritable: true },
    userTokenAccount: {
      value: input.userTokenAccount ?? null,
      isWritable: true,
    },
    tokenMint: { value: input.tokenMint ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  }
  const accounts = originalAccounts as Record<keyof typeof originalAccounts, ResolvedAccount>

  // Original args.
  const args = { ...input }

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value = '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId')
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.userAccount),
      getAccountMeta(accounts.stakeAccount),
      getAccountMeta(accounts.userTokenAccount),
      getAccountMeta(accounts.tokenMint),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getStakeInstructionDataEncoder().encode(args as StakeInstructionDataArgs),
    programAddress,
  } as StakeInstruction<TProgramAddress, TAccountUser, TAccountUserAccount, TAccountStakeAccount, TAccountUserTokenAccount, TAccountTokenMint, TAccountVault, TAccountConfig, TAccountTokenProgram, TAccountAssociatedTokenProgram, TAccountSystemProgram>)
}

export type ParsedStakeInstruction<
  TProgram extends string = typeof STAKING_TEMPLATE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>
  accounts: {
    user: TAccountMetas[0]
    /** created on first stake, reused on subsequent ones */
    userAccount: TAccountMetas[1]
    /** one per stake — seed includes `id` so users can stake multiple times */
    stakeAccount: TAccountMetas[2]
    userTokenAccount: TAccountMetas[3]
    tokenMint: TAccountMetas[4]
    vault: TAccountMetas[5]
    config: TAccountMetas[6]
    tokenProgram: TAccountMetas[7]
    associatedTokenProgram: TAccountMetas[8]
    systemProgram: TAccountMetas[9]
  }
  data: StakeInstructionData
}

export function parseStakeInstruction<TProgram extends string, TAccountMetas extends readonly AccountMeta[]>(
  instruction: Instruction<TProgram> & InstructionWithAccounts<TAccountMetas> & InstructionWithData<ReadonlyUint8Array>,
): ParsedStakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 10) {
    // TODO: Coded error.
    throw new Error('Not enough accounts')
  }
  let accountIndex = 0
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!
    accountIndex += 1
    return accountMeta
  }
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      userAccount: getNextAccount(),
      stakeAccount: getNextAccount(),
      userTokenAccount: getNextAccount(),
      tokenMint: getNextAccount(),
      vault: getNextAccount(),
      config: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getStakeInstructionDataDecoder().decode(instruction.data),
  }
}
