minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - next
  - '@next/*'
  - react
  - react-dom
  - '@solana/client'
  - '@solana/react-hooks'
  - '@solana/kit'
  - '@solana/kit-plugin-wallet'
  - '@solana-program/system'
  - '@solana-program/token'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - bigint-buffer
  - bufferutil
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
packages:
  - community/*
  - kit/*
  - pinocchio/*
  - web3js/*
