import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from '@/components/app-providers'
import React from 'react'
import { WalletUI } from '@/components/wallet-ui'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Tokegateddapp',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`relative px-10`}>
        <AppProviders>
          <nav className="flex justify-between items-center py-4">
            <Link href="/" className="text-xl font-bold">
              Token Gated Dapp
            </Link>
            <WalletUI />
          </nav>
          {children}
        </AppProviders>
      </body>
    </html>
  )
}
// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}
