/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from '@solana/kit'

export const STAKE_ACCOUNT_DISCRIMINATOR = new Uint8Array([80, 158, 67, 124, 50, 189, 192, 255])

export function getStakeAccountDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(STAKE_ACCOUNT_DISCRIMINATOR)
}

export type StakeAccount = {
  discriminator: ReadonlyUint8Array
  owner: Address
  /** lamports locked in this particular stake */
  amount: bigint
  /** unix timestamp — used to enforce freeze period & compute rewards */
  stakedAt: bigint
  bump: number
}

export type StakeAccountArgs = {
  owner: Address
  /** lamports locked in this particular stake */
  amount: number | bigint
  /** unix timestamp — used to enforce freeze period & compute rewards */
  stakedAt: number | bigint
  bump: number
}

/** Gets the encoder for {@link StakeAccountArgs} account data. */
export function getStakeAccountEncoder(): FixedSizeEncoder<StakeAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['owner', getAddressEncoder()],
      ['amount', getU64Encoder()],
      ['stakedAt', getI64Encoder()],
      ['bump', getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: STAKE_ACCOUNT_DISCRIMINATOR }),
  )
}

/** Gets the decoder for {@link StakeAccount} account data. */
export function getStakeAccountDecoder(): FixedSizeDecoder<StakeAccount> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['owner', getAddressDecoder()],
    ['amount', getU64Decoder()],
    ['stakedAt', getI64Decoder()],
    ['bump', getU8Decoder()],
  ])
}

/** Gets the codec for {@link StakeAccount} account data. */
export function getStakeAccountCodec(): FixedSizeCodec<StakeAccountArgs, StakeAccount> {
  return combineCodec(getStakeAccountEncoder(), getStakeAccountDecoder())
}

export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<StakeAccount, TAddress>
export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<StakeAccount, TAddress>
export function decodeStakeAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<StakeAccount, TAddress> | MaybeAccount<StakeAccount, TAddress> {
  return decodeAccount(encodedAccount as MaybeEncodedAccount<TAddress>, getStakeAccountDecoder())
}

export async function fetchStakeAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<StakeAccount, TAddress>> {
  const maybeAccount = await fetchMaybeStakeAccount(rpc, address, config)
  assertAccountExists(maybeAccount)
  return maybeAccount
}

export async function fetchMaybeStakeAccount<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<StakeAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config)
  return decodeStakeAccount(maybeAccount)
}

export async function fetchAllStakeAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<StakeAccount>[]> {
  const maybeAccounts = await fetchAllMaybeStakeAccount(rpc, addresses, config)
  assertAccountsExist(maybeAccounts)
  return maybeAccounts
}

export async function fetchAllMaybeStakeAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<StakeAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config)
  return maybeAccounts.map((maybeAccount) => decodeStakeAccount(maybeAccount))
}

export function getStakeAccountSize(): number {
  return 57
}
