/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseClaimInstruction,
  parseInitializePoolInstruction,
  parseStakeInstruction,
  parseUnstakeInstruction,
  type ParsedClaimInstruction,
  type ParsedInitializePoolInstruction,
  type ParsedStakeInstruction,
  type ParsedUnstakeInstruction,
} from "../instructions";

export const STAKING_TEMPLATE_PROGRAM_ADDRESS =
  "RyFaKyDtxWbmN2ffdgHBdASic8kGhREJEGVQiDmm6aT" as Address<"RyFaKyDtxWbmN2ffdgHBdASic8kGhREJEGVQiDmm6aT">;

export enum StakingTemplateAccount {
  StakeAccount,
  StakeConfig,
  UserAccount,
}

export function identifyStakingTemplateAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StakingTemplateAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([80, 158, 67, 124, 50, 189, 192, 255]),
      ),
      0,
    )
  ) {
    return StakingTemplateAccount.StakeAccount;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([238, 151, 43, 3, 11, 151, 63, 176]),
      ),
      0,
    )
  ) {
    return StakingTemplateAccount.StakeConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 33, 136, 16, 186, 110, 242, 127]),
      ),
      0,
    )
  ) {
    return StakingTemplateAccount.UserAccount;
  }
  throw new Error(
    "The provided account could not be identified as a stakingTemplate account.",
  );
}

export enum StakingTemplateInstruction {
  Claim,
  InitializePool,
  Stake,
  Unstake,
}

export function identifyStakingTemplateInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): StakingTemplateInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([62, 198, 214, 193, 213, 159, 108, 210]),
      ),
      0,
    )
  ) {
    return StakingTemplateInstruction.Claim;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([95, 180, 10, 172, 84, 174, 232, 40]),
      ),
      0,
    )
  ) {
    return StakingTemplateInstruction.InitializePool;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([206, 176, 202, 18, 200, 209, 179, 108]),
      ),
      0,
    )
  ) {
    return StakingTemplateInstruction.Stake;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([90, 95, 107, 42, 205, 124, 50, 225]),
      ),
      0,
    )
  ) {
    return StakingTemplateInstruction.Unstake;
  }
  throw new Error(
    "The provided instruction could not be identified as a stakingTemplate instruction.",
  );
}

export type ParsedStakingTemplateInstruction<
  TProgram extends string = "RyFaKyDtxWbmN2ffdgHBdASic8kGhREJEGVQiDmm6aT",
> =
  | ({
      instructionType: StakingTemplateInstruction.Claim;
    } & ParsedClaimInstruction<TProgram>)
  | ({
      instructionType: StakingTemplateInstruction.InitializePool;
    } & ParsedInitializePoolInstruction<TProgram>)
  | ({
      instructionType: StakingTemplateInstruction.Stake;
    } & ParsedStakeInstruction<TProgram>)
  | ({
      instructionType: StakingTemplateInstruction.Unstake;
    } & ParsedUnstakeInstruction<TProgram>);

export function parseStakingTemplateInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedStakingTemplateInstruction<TProgram> {
  const instructionType = identifyStakingTemplateInstruction(instruction);
  switch (instructionType) {
    case StakingTemplateInstruction.Claim: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StakingTemplateInstruction.Claim,
        ...parseClaimInstruction(instruction),
      };
    }
    case StakingTemplateInstruction.InitializePool: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StakingTemplateInstruction.InitializePool,
        ...parseInitializePoolInstruction(instruction),
      };
    }
    case StakingTemplateInstruction.Stake: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StakingTemplateInstruction.Stake,
        ...parseStakeInstruction(instruction),
      };
    }
    case StakingTemplateInstruction.Unstake: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: StakingTemplateInstruction.Unstake,
        ...parseUnstakeInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
