[package]
name = "tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
client.workspace = true
interface.workspace = true
litesvm.workspace = true
solana-address.workspace = true
solana-instruction.workspace = true
solana-instruction-error.workspace = true
solana-keypair.workspace = true
solana-signer.workspace = true
solana-transaction.workspace = true
solana-transaction-error.workspace = true
